For some reason one of these errors thrown by Discord.js in an async function fires uncaughtException not unhandledRejection, and the fix is to just not pass that rejection into the eventemitter??
DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/sheep/floofy-bot/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/sheep/floofy-bot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:399:20)
    at async SequentialHandler.queueRequest (/home/sheep/floofy-bot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)
    at async REST.request (/home/sheep/floofy-bot/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
    at async TextChannel.send (/home/sheep/floofy-bot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:162:15)
    at async Client.<anonymous> (/home/sheep/floofy-bot/src/index.ts:193:7) {
  requestBody: {
    files: [],
    json: {
      content: '<:ping:719277539113041930>',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: [Object],
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: { message: 'Missing Permissions', code: 50013 },
  code: 50013,
  status: 403,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/775797057926856754/messages'
}
uncaughtException fired, so I will now commit exit(1)